### ISSUE TITLE
Afterburner target: curl not found

### ISSUE THREAD

**Issue by NGoetz** [smash-transport/smash-analysis#80] opened 2023-12-12 10:08 UTC
The afterburner target uses curl to download exernal input (https://github.com/smash-transport/smash-analysis/blob/main/test/afterburner/CMakeLists.txt line 19). Inside the latest rc container, this fails because the of the error:
```
bash: curl: command not found
```
outside the container, this works fine.

**Comment by AxelKrypton** [comment] 2023-12-12 10:13
I will add it and replace the container. `wget` is available and I thought it was enough as we work in GNU environment. 🙈 I will let you know as soon as I am done.

**Comment by AxelKrypton** [comment] 2023-12-12 17:14
The new container is on the Virgo cluster.

```console
asciarra@lxbk1131:/lustre/hyihp/AG-Elfner$ ls -1
smash-devel-3.1rc-max.sif
smash-devel-3.1rc-max_with_curl.sif
asciarra@lxbk1131:/lustre/hyihp/AG-Elfner$ singularity exec smash-devel-3.1rc-max.sif smash --version
SMASH-3.1rc-3-gc02aec6e6
Branch   : release-3.1
System   : Linux-5.10.0-26-amd64
Compiler : GNU 11.4.0
Build    : Release
Date     : 2023-12-11T14:44:44
asciarra@lxbk1131:/lustre/hyihp/AG-Elfner$ singularity exec smash-devel-3.1rc-max_with_curl.sif smash --version
SMASH-3.1rc-4-gb60a221a5
Branch   : release-3.1
System   : Linux-5.10.0-26-amd64
Compiler : GNU 11.4.0
Build    : Release
Date     : 2023-12-12T14:53:11
asciarra@lxbk1131:/lustre/hyihp/AG-Elfner$ singularity exec smash-devel-3.1rc-max_with_curl.sif which curl
/usr/bin/curl
asciarra@lxbk1131:/lustre/hyihp/AG-Elfner$ singularity exec smash-devel-3.1rc-max.sif which curl
asciarra@lxbk1131:/lustre/hyihp/AG-Elfner$
```

@NGoetz Close this issue if the problem is solved.

**Closed** 2023-12-13 06:07 UTC
